//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projectDBEntities5 : DbContext
    {
        public projectDBEntities5()
            : base("name=projectDBEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Business_tbl> Business_tbl { get; set; }
        public virtual DbSet<Category_tbl> Category_tbl { get; set; }
        public virtual DbSet<Events_tbl> Events_tbl { get; set; }
        public virtual DbSet<Schedule_tbl> Schedule_tbl { get; set; }
        public virtual DbSet<Users_tbl> Users_tbl { get; set; }
        public virtual DbSet<BusinessOpeningHours_tbl> BusinessOpeningHours_tbl { get; set; }
    }
}
